version: '3'

# change this to match one of your existing nets that you want to verify
networks:
  my-test-bridge:

services:
  pinger:
    image: nicgrobler/pinger:3.0.0
    deploy:
      # set this as you want - scale also works when running
      replicas: 3 
    env_file:
      - .env
    command: /go/bin/pinger
    environment:
      - GELF_URL=$GELF_URL
      - STARTUP_DELAY_SECONDS=$STARTUP_DELAY_SECONDS
      - STARTUP_RETRIES=$STARTUP_RETRIES
      - STARTUP_RETRIES_DELAY_SECONDS=$STARTUP_RETRIES_DELAY_SECONDS
      - STACK_NAME=$STACK_NAME
      - SERVICE_NAME=$SERVICE_NAME
      - CYCLE_TIME_SECONDS=$CYCLE_TIME_SECONDS
      - CONNECTION_TIMEOUT_SECONDS=$CONNECTION_TIMEOUT_SECONDS
      - IDLE_CONNECTION_TIMEOUT_SECONDS=$IDLE_CONNECTION_TIMEOUT_SECONDS
      - PORT=$PORT
    networks:
      # change this to match one of your existing nets that you want to verify
      my-test-bridge:
          
