version: '3'

networks:
  my-test-bridge:

services:
  pinger:
    image: nicgrobler/pinger:v1.0.0
    deploy:
      replicas: 3 
    env_file:
      - .env
    command: /go/bin/pinger
    environment:
      - GELF_URL=$GELF_URL
      - STARTUP_RETRIES=$STARTUP_RETRIES
      - STARTUP_RETRIES_DELAY_SECONDS=$STARTUP_RETRIES_DELAY_SECONDS
      - STACK_NAME=$STACK_NAME
      - CYCLE_TIME_SECONDS=$CYCLE_TIME_SECONDS
      - CONNECTION_TIMEOUT_SECONDS=$CONNECTION_TIMEOUT_SECONDS
      - IDLE_CONNECTION_TIMEOUT_SECONDS=$IDLE_CONNECTION_TIMEOUT_SECONDS
      - PORT=$PORT
    networks:
      my-test-bridge:
          
