name: Push to Docker

on: 
   push:
     tags:
       - 'v*'

jobs:
  github:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v1

      - name: Login to github registry
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build :tag
        if: success()
        run: docker build -t hub.docker.com/repository/docker/nicgrobler/${{ github.repository }}/app:${IMAGE_TAG} .

      - name: Push to docker hub :tag
        if: success()
        uses: actions-hub/docker@master
        with:
          args: docker push hub.docker.com/repository/docker/nicgrobler/${{ github.repository }}/app:${IMAGE_TAG}
